title: Horizons - a retro gaming blog
email: tnaires@gmail.com
description: >
  This blog is mainly about retro gaming. Here I will write about all the
  good moments I had with videogames since the early eighites, when I
  started to play them.
baseurl: ""
url: "http://tnaires.github.io/horizons/"
twitter_username: tnaires
github_username: tnaires

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
