title: Horizons - blog de jogos :)
email: tnaires@gmail.com
description: >
  Este é um blog sobre jogos de videogame! Procurarei escrever aqui sobre
  todos os jogos que marcaram minha infância e adolescência, e também
  sobre os que continuam me marcando atualmente.
baseurl: ""
url: "http://tnaires.github.io/horizons/"
twitter_username: tnaires
github_username: tnaires
timezone: America/Recife
permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
